### ISSUE TITLE
Dockerization ? 

### ISSUE THREAD

**Issue by gkowalski** [ui-icts/deidentnote#1]
Does your team think there instructions get us in the ballpark for running this app : 

https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by jschappet** [comment]
@gkowalski It should be easy to get that going. I'll take a look, I know we have a few other projects using Docker, and some using Habitat.

**Comment by jschappet** [comment]
You can now run: 

    docker build -t schappetj/deidentnote .
    docker run -p 9876:3000 schappetj/deidentnote

 Then go to:  http://localhost:9876/
